import { createHash } from "node:crypto";

export type PeriodType = "daily" | "weekly" | "monthly" | "yearly";
export type PlanCode = "free" | "basic" | "premium";
export type HoroscopeStatus = "draft" | "approved" | "rejected" | "queued" | "sent";
export type DeliveryStatus = "queued" | "sent" | "failed";
export interface MockContext { sessionId: string; userId: string }
// ...types unchanged
export interface BirthProfileInput { birthDate:string; birthTime?:string; birthTimeUnknown:boolean; birthPlaceText:string; timezone:string; consentBirthData:boolean; }
export interface BirthProfile extends BirthProfileInput { id:string; userId:string; createdAt:string; }
export interface ChartSnapshot { id:string; userId:string; birthProfileId:string; calculation_profile_code:"TH_MOCK_MVP_V1"; engine:"mock"; engine_version:"0.1.0"; ephemeris_source:"mock"; datetime_utc:string; julian_day_ut:number; planets:Record<string,{sign_index:number;longitude_deg:number;retrograde:boolean}>; houses:{system:"mock_whole_sign";ascendant_deg:number|null;cusps_deg:number[]}; aspects:Array<{planet_a:string;planet_b:string;type:string;orb_deg:number}>; warnings:string[]; calculation_hash:string; }
export interface HoroscopeResult { id:string; userId:string; periodType:PeriodType; periodKey:string; chartSnapshotId:string; status:HoroscopeStatus; rule_hits_json:Array<{rule_id:string;category:string;weight:number;source_hash:string}>; content_json:{title:string;summary:string;sections:Array<{heading:string;body:string}>;disclaimer:string}; approvedAt?:string; approvedBy?:string; rejectedAt?:string; rejectedBy?:string; }
export interface OutboundMessage { id:string; userId:string; horoscopeResultId:string; topicCode:string; channel:"mock"; title:string; body:string; status:"queued"|"sent"; createdAt:string; }
export interface DeliveryAttempt { id:string; outboundMessageId:string; gateway:"mock"; status:DeliveryStatus; attemptedAt:string; providerMessageId?:string; }
export type ConsentType = "terms"|"privacy"|"birth_data"|"service_notification"|"marketing_notification";
export interface ConsentRecord { id:string; userId:string; consentType:ConsentType; accepted:boolean; recordedAt:string; revokedAt?:string; source:"mock_web"; }
export interface NotificationPreference { id:string; userId:string; topicCode:string; channel:"mock"; enabled:boolean; updatedAt:string; }
export interface AccountDeletionRequest { id:string; userId:string; status:"requested"; requestedAt:string; }
export interface UserPrivacyExport { userId:string; planCode:PlanCode; birthProfiles:BirthProfile[]; chartSnapshots:ChartSnapshot[]; horoscopeResults:HoroscopeResult[]; outboundMessages:OutboundMessage[]; deliveryAttempts:DeliveryAttempt[]; consentRecords:ConsentRecord[]; notificationPreferences:NotificationPreference[]; accountDeletionRequests:AccountDeletionRequest[]; }
export interface AuditLogEntry { id:string; actorId:string; action:"birth_profile_saved"|"chart_snapshot_stored"|"horoscope_generated"|"draft_approved"|"draft_rejected"|"outbound_queued"|"delivery_attempt_recorded"|"admin_access_denied"|"admin_session_started"|"admin_content_approved"|"admin_content_rejected"|"admin_outbound_queued"|"consent_recorded"|"birth_profile_deleted"|"account_deletion_requested"|"notification_unsubscribed"|"user_data_exported"; targetId:string; createdAt:string; metadata:Record<string,string>; }
export interface MockMvpState { userPlans:Record<string,PlanCode>; birthProfiles:BirthProfile[]; chartSnapshots:ChartSnapshot[]; horoscopeResults:HoroscopeResult[]; outboundMessages:OutboundMessage[]; deliveryAttempts:DeliveryAttempt[]; auditLogs:AuditLogEntry[]; consentRecords:ConsentRecord[]; notificationPreferences:NotificationPreference[]; accountDeletionRequests:AccountDeletionRequest[]; deletedBirthProfileIds:Record<string,string>; deactivatedUserIds:Record<string,string>; }

const entitlements: Record<PlanCode, PeriodType[]> = { free:["daily"], basic:["daily","weekly"], premium:["daily","weekly","monthly","yearly"] };
const disclaimer = "เนื้อหานี้จัดทำเพื่อความบันเทิงและการทบทวนตนเองเท่านั้น ไม่ใช่คำแนะนำทางการแพทย์ การเงิน กฎหมาย หรือการตัดสินใจที่มีความเสี่ยงสูง";
let registry = new Map<string, MockMvpState>();
function getState(sessionId:string): MockMvpState { const key=sessionId.trim()||"dev-default"; if(!registry.has(key)) registry.set(key, {userPlans:{},birthProfiles:[],chartSnapshots:[],horoscopeResults:[],outboundMessages:[],deliveryAttempts:[],auditLogs:[],consentRecords:[],notificationPreferences:[],accountDeletionRequests:[],deletedBirthProfileIds:{},deactivatedUserIds:{}}); return registry.get(key)!; }
export function resetMockMvpState(planCode: PlanCode = "premium"): void { registry = new Map(); const s=getState("dev-default"); s.userPlans["user_mock_001"]=planCode; }
resetMockMvpState();
export function getMockMvpState(sessionId="dev-default"): MockMvpState { return structuredClone(getState(sessionId)); }
export function canViewPeriod(planCode:PlanCode, periodType:PeriodType):boolean { return entitlements[planCode].includes(periodType); }
export function setMockUserPlan(userId:string, planCode:PlanCode, sessionId="dev-default"):void { getState(sessionId).userPlans[userId]=planCode; }
export function saveBirthProfile(input:BirthProfileInput, context:MockContext={sessionId:"dev-default",userId:"user_mock_001"}, now=new Date("2026-05-03T09:00:00.000Z")):BirthProfile { validateBirthProfile(input); const s=getState(context.sessionId); requireActiveUser(s,context.userId); if(!s.userPlans[context.userId]) s.userPlans[context.userId]="premium"; const profile={...input,id:`birth_${s.birthProfiles.length+1}`,userId:context.userId,birthPlaceText:input.birthPlaceText.trim(),timezone:input.timezone.trim(),createdAt:now.toISOString()}; s.birthProfiles.push(profile); if(input.consentBirthData) recordConsent(context,"birth_data",true,now); writeAudit(s,"system","birth_profile_saved",profile.id,now,{userId:profile.userId}); return profile; }
export function callMockAstroCalc(profile:BirthProfile):ChartSnapshot { const hashInput=[profile.birthDate,profile.birthTimeUnknown?"unknown":profile.birthTime??"",profile.birthPlaceText,profile.timezone,"TH_MOCK_MVP_V1"].join("|"); const calculationHash=sha256(hashInput); const seed=Number.parseInt(calculationHash.slice(0,8),16); return {id:`chart_${profile.userId}_${profile.id}_${calculationHash.slice(0,8)}`,userId:profile.userId,birthProfileId:profile.id,calculation_profile_code:"TH_MOCK_MVP_V1",engine:"mock",engine_version:"0.1.0",ephemeris_source:"mock",datetime_utc:`${profile.birthDate}T00:00:00.000Z`,julian_day_ut:2461163.5,planets:{sun:mockPlanet(seed,0),moon:mockPlanet(seed,1),mercury:mockPlanet(seed,2),venus:mockPlanet(seed,3),mars:mockPlanet(seed,4)},houses:{system:"mock_whole_sign",ascendant_deg:profile.birthTimeUnknown?null:(seed%36000)/100,cusps_deg:profile.birthTimeUnknown?[]:Array.from({length:12},(_,i)=>((seed+i*3000)%36000)/100)},aspects:[{planet_a:"moon",planet_b:"venus",type:"trine",orb_deg:2.5},{planet_a:"mars",planet_b:"mercury",type:"square",orb_deg:3.1}],warnings:profile.birthTimeUnknown?["UNKNOWN_BIRTH_TIME"]:[],calculation_hash:calculationHash}; }
export function storeChartSnapshot(snapshot:ChartSnapshot, sessionId="dev-default", now=new Date("2026-05-03T09:01:00.000Z")):ChartSnapshot { const s=getState(sessionId); requireActiveUser(s,snapshot.userId); requireActiveBirthProfile(s,snapshot.userId,snapshot.birthProfileId); const existing=s.chartSnapshots.find(c=>c.userId===snapshot.userId && c.birthProfileId===snapshot.birthProfileId && c.calculation_hash===snapshot.calculation_hash); if(existing) return existing; s.chartSnapshots.push(snapshot); writeAudit(s,"system","chart_snapshot_stored",snapshot.id,now,{calculationProfileCode:snapshot.calculation_profile_code}); return snapshot; }
export function generateChartSnapshotForBirthProfile(profile:BirthProfile, context:MockContext, now=new Date("2026-05-03T09:01:00.000Z")):ChartSnapshot { const s=getState(context.sessionId); if(profile.userId!==context.userId) throw new Error("Unauthorized: birth profile does not belong to current user."); requireActiveBirthProfile(s,context.userId,profile.id); return storeChartSnapshot(callMockAstroCalc(profile),context.sessionId,now); }
export function generateHoroscopeResult(input:{chartSnapshot:ChartSnapshot;periodType:PeriodType;periodKey:string;now?:Date;sessionId?:string;}):HoroscopeResult{ const s=getState(input.sessionId??"dev-default"); requireActiveUser(s,input.chartSnapshot.userId); requireActiveBirthProfile(s,input.chartSnapshot.userId,input.chartSnapshot.birthProfileId); const existing=s.horoscopeResults.find(r=>r.userId===input.chartSnapshot.userId&&r.chartSnapshotId===input.chartSnapshot.id&&r.periodType===input.periodType&&r.periodKey===input.periodKey); if(existing) return existing; const now=input.now??new Date("2026-05-03T09:02:00.000Z"); const ruleHits=createRuleHits(input.chartSnapshot,input.periodType); const result:HoroscopeResult={id:`horo_${input.chartSnapshot.userId}_${input.periodType}_${input.periodKey.replace(/[^a-zA-Z0-9]/g,"_")}`,userId:input.chartSnapshot.userId,periodType:input.periodType,periodKey:input.periodKey,chartSnapshotId:input.chartSnapshot.id,status:"draft",rule_hits_json:ruleHits,content_json:renderSafeThaiContent(input.periodType,input.periodKey,ruleHits)}; s.horoscopeResults.push(result); writeAudit(s,"system","horoscope_generated",result.id,now,{periodType:input.periodType}); return result; }
export function getEntitledHoroscope(periodType:PeriodType, context:MockContext={sessionId:"dev-default",userId:"user_mock_001"}):HoroscopeResult|undefined{ const s=getState(context.sessionId); const plan=s.userPlans[context.userId]??"free"; if(!canViewPeriod(plan,periodType)) return undefined; return s.horoscopeResults.find(r=>r.userId===context.userId&&r.periodType===periodType); }
function requireHoroscopeResult(resultId:string, sessionId:string){ const r=getState(sessionId).horoscopeResults.find(c=>c.id===resultId); if(!r) throw new Error(`Horoscope result not found: ${resultId}`); return r; }
export function approveDraft(resultId:string, actorId="dev_admin_mock", sessionId="dev-default", now=new Date("2026-05-03T09:03:00.000Z")):HoroscopeResult { const s=getState(sessionId); const r=requireHoroscopeResult(resultId,sessionId); r.status="approved"; r.approvedAt=now.toISOString(); r.approvedBy=actorId; writeAudit(s,actorId,"draft_approved",r.id,now,{periodType:r.periodType}); return r; }
export function rejectDraft(resultId:string, actorId:string, sessionId="dev-default", now=new Date("2026-05-03T09:03:30.000Z")):HoroscopeResult { const s=getState(sessionId); const r=requireHoroscopeResult(resultId,sessionId); if(r.status!=="draft") throw new Error("Only draft horoscope results can be rejected."); r.status="rejected"; r.rejectedAt=now.toISOString(); r.rejectedBy=actorId; writeAudit(s,actorId,"draft_rejected",r.id,now,{periodType:r.periodType}); return r; }
export function queueMockOutboundMessage(resultId:string, sessionId="dev-default", now=new Date("2026-05-03T09:04:00.000Z")):OutboundMessage{ const s=getState(sessionId); const r=requireHoroscopeResult(resultId,sessionId); if(r.status!=="approved") throw new Error("Only approved horoscope results can be queued."); const topicCode=`${r.periodType}_horoscope`; requireNotificationAllowed(s,r.userId,topicCode); const key=`${r.id}:${r.userId}:${topicCode}:${r.periodKey}`; const existing=s.outboundMessages.find(m=>`${m.horoscopeResultId}:${m.userId}:${m.topicCode}:${requireHoroscopeResult(m.horoscopeResultId,sessionId).periodKey}`===key&&(m.status==="queued"||m.status==="sent")); if(existing) return existing; const m:OutboundMessage={id:`out_${s.outboundMessages.length+1}`,userId:r.userId,horoscopeResultId:r.id,topicCode,channel:"mock",title:r.content_json.title,body:`${r.content_json.summary} เพื่อความบันเทิงและการทบทวนตนเอง`,status:"queued",createdAt:now.toISOString()}; s.outboundMessages.push(m); writeAudit(s,"system","outbound_queued",m.id,now,{resultId}); return m; }
export function recordMockDeliveryAttempt(messageId:string, sessionId="dev-default", now=new Date("2026-05-03T09:05:00.000Z")):DeliveryAttempt{ const s=getState(sessionId); const m=s.outboundMessages.find(c=>c.id===messageId); if(!m) throw new Error(`Outbound message not found: ${messageId}`); const ex=s.deliveryAttempts.find(a=>a.outboundMessageId===m.id&&a.status==="sent"); if(ex){m.status="sent"; return ex;} m.status="sent"; const a:DeliveryAttempt={id:`attempt_${s.deliveryAttempts.length+1}`,outboundMessageId:m.id,gateway:"mock",status:"sent",attemptedAt:now.toISOString(),providerMessageId:`mock_provider_${m.id}`}; s.deliveryAttempts.push(a); writeAudit(s,"system","delivery_attempt_recorded",a.id,now,{messageId}); return a; }
export function getMockPeriodKey(periodType: PeriodType): string { return {daily:"2026-05-03",weekly:"2026-W18",monthly:"2026-05",yearly:"2026"}[periodType]; }
export function bootstrapDemoFlow(sessionId="dev-default", userId="user_mock_001"):void{ const s=getState(sessionId); if(s.birthProfiles.some(p=>p.userId===userId)) return; const bp=saveBirthProfile({birthDate:"1992-08-15",birthTime:"07:30",birthTimeUnknown:false,birthPlaceText:"Bangkok",timezone:"Asia/Bangkok",consentBirthData:true},{sessionId,userId}); const cs=storeChartSnapshot(callMockAstroCalc(bp),sessionId); (["daily","weekly","monthly","yearly"] as PeriodType[]).forEach((p)=>generateHoroscopeResult({chartSnapshot:cs,periodType:p,periodKey:getMockPeriodKey(p),sessionId})); }
export function runMockEndToEndFlow(input:BirthProfileInput, context:MockContext={sessionId:"dev-default",userId:"user_mock_001"}){ const bp=saveBirthProfile(input,context); const cs=storeChartSnapshot(callMockAstroCalc(bp),context.sessionId); const generated=( ["daily","weekly","monthly","yearly"] as PeriodType[]).map((p)=>generateHoroscopeResult({chartSnapshot:cs,periodType:p,periodKey:getMockPeriodKey(p),sessionId:context.sessionId})); const approved=approveDraft(generated[0].id,"dev_admin_mock",context.sessionId); const msg=queueMockOutboundMessage(approved.id,context.sessionId); const attempt=recordMockDeliveryAttempt(msg.id,context.sessionId); return {birthProfile:bp,chartSnapshot:cs,generatedResults:generated,approvedDraft:approved,outboundMessage:msg,deliveryAttempt:attempt}; }
export function recordConsent(context:MockContext, consentType:ConsentType, accepted:boolean, now=new Date("2026-05-03T09:00:30.000Z")):ConsentRecord{ const s=getState(context.sessionId); const existing=s.consentRecords.find(c=>c.userId===context.userId&&c.consentType===consentType&&c.accepted===accepted&&!c.revokedAt); if(existing) return existing; const record:ConsentRecord={id:`consent_${s.consentRecords.length+1}`,userId:context.userId,consentType,accepted,recordedAt:now.toISOString(),source:"mock_web"}; if(!accepted) record.revokedAt=now.toISOString(); s.consentRecords.push(record); writeAudit(s,"system","consent_recorded",record.id,now,{consentType,accepted:String(accepted)}); return record; }
export function exportUserData(context:MockContext, now=new Date("2026-05-03T09:06:30.000Z")):UserPrivacyExport{ const s=getState(context.sessionId); const userMessages=s.outboundMessages.filter(m=>m.userId===context.userId); const messageIds=new Set(userMessages.map(m=>m.id)); const data:UserPrivacyExport={userId:context.userId,planCode:s.userPlans[context.userId]??"free",birthProfiles:s.birthProfiles.filter(p=>p.userId===context.userId),chartSnapshots:s.chartSnapshots.filter(c=>c.userId===context.userId),horoscopeResults:s.horoscopeResults.filter(r=>r.userId===context.userId),outboundMessages:userMessages,deliveryAttempts:s.deliveryAttempts.filter(a=>messageIds.has(a.outboundMessageId)),consentRecords:s.consentRecords.filter(c=>c.userId===context.userId),notificationPreferences:s.notificationPreferences.filter(p=>p.userId===context.userId),accountDeletionRequests:s.accountDeletionRequests.filter(r=>r.userId===context.userId)}; writeAudit(s,"system","user_data_exported","user_data_export",now,{}); return structuredClone(data); }
export function deleteBirthProfile(context:MockContext, birthProfileId:string, now=new Date("2026-05-03T09:07:00.000Z")):void{ const s=getState(context.sessionId); const profile=s.birthProfiles.find(p=>p.id===birthProfileId&&p.userId===context.userId); if(!profile) throw new Error(`Birth profile not found: ${birthProfileId}`); s.deletedBirthProfileIds[birthProfileId]=now.toISOString(); s.birthProfiles=s.birthProfiles.filter(p=>p.id!==birthProfileId); const chartIds=new Set(s.chartSnapshots.filter(c=>c.birthProfileId===birthProfileId&&c.userId===context.userId).map(c=>c.id)); s.chartSnapshots=s.chartSnapshots.filter(c=>!chartIds.has(c.id)); s.horoscopeResults=s.horoscopeResults.filter(r=>!(r.userId===context.userId&&chartIds.has(r.chartSnapshotId))); writeAudit(s,"system","birth_profile_deleted",birthProfileId,now,{userId:context.userId}); }
export function requestAccountDeletion(context:MockContext, now=new Date("2026-05-03T09:07:30.000Z")):AccountDeletionRequest{ const s=getState(context.sessionId); const existing=s.accountDeletionRequests.find(r=>r.userId===context.userId&&r.status==="requested"); if(existing) return existing; const request:AccountDeletionRequest={id:`acctdel_${s.accountDeletionRequests.length+1}`,userId:context.userId,status:"requested",requestedAt:now.toISOString()}; s.accountDeletionRequests.push(request); s.deactivatedUserIds[context.userId]=now.toISOString(); writeAudit(s,"system","account_deletion_requested",request.id,now,{userId:context.userId}); return request; }
export function unsubscribeNotifications(context:MockContext, topicCode="all", now=new Date("2026-05-03T09:08:00.000Z")):NotificationPreference{ const s=getState(context.sessionId); const existing=s.notificationPreferences.find(p=>p.userId===context.userId&&p.topicCode===topicCode&&p.channel==="mock"); if(existing){ existing.enabled=false; existing.updatedAt=now.toISOString(); writeAudit(s,"system","notification_unsubscribed",existing.id,now,{topicCode}); return existing; } const preference:NotificationPreference={id:`pref_${s.notificationPreferences.length+1}`,userId:context.userId,topicCode,channel:"mock",enabled:false,updatedAt:now.toISOString()}; s.notificationPreferences.push(preference); writeAudit(s,"system","notification_unsubscribed",preference.id,now,{topicCode}); return preference; }
function requireActiveUser(s:MockMvpState,userId:string):void{ if(s.deactivatedUserIds[userId]) throw new Error("User is deactivated."); }
function requireActiveBirthProfile(s:MockMvpState,userId:string,birthProfileId:string):void{ requireActiveUser(s,userId); if(s.deletedBirthProfileIds[birthProfileId]) throw new Error("Birth profile has been deleted."); if(!s.birthProfiles.some(p=>p.id===birthProfileId&&p.userId===userId)) throw new Error(`Birth profile not found: ${birthProfileId}`); }
function requireNotificationAllowed(s:MockMvpState,userId:string,topicCode:string):void{ requireActiveUser(s,userId); const blocked=s.notificationPreferences.some(p=>p.userId===userId&&p.channel==="mock"&&!p.enabled&&(p.topicCode==="all"||p.topicCode===topicCode)); if(blocked) throw new Error("Notification delivery is disabled for this user."); }
function validateBirthProfile(input: BirthProfileInput): void { if (!/^\d{4}-\d{2}-\d{2}$/.test(input.birthDate)) throw new Error("Birth date must use YYYY-MM-DD."); if(!input.birthTimeUnknown&&!/^\d{2}:\d{2}$/.test(input.birthTime??"")) throw new Error("Birth time is required unless marked unknown."); if(!input.birthPlaceText.trim()) throw new Error("Birth place is required."); if(!input.timezone.trim()) throw new Error("Timezone is required."); if(!input.consentBirthData) throw new Error("Birth data consent is required."); }
function mockPlanet(seed:number,offset:number){ const longitude=((seed+offset*4321)%36000)/100; return {sign_index:Math.floor(longitude/30),longitude_deg:longitude,retrograde:(seed+offset)%5===0}; }
function createRuleHits(chartSnapshot: ChartSnapshot, periodType: PeriodType){ const categories=["overview","work_study","money","relationship","wellness","advice"]; const base=Number.parseInt(chartSnapshot.calculation_hash.slice(0,6),16); return categories.map((category,index)=>({rule_id:`MOCK_${periodType.toUpperCase()}_${category.toUpperCase()}_${String(index+1).padStart(3,"0")}`,category,weight:((base+index)%3)+1,source_hash:chartSnapshot.calculation_hash})); }
function renderSafeThaiContent(periodType:PeriodType,periodKey:string,ruleHits:HoroscopeResult["rule_hits_json"]){ const titleMap={daily:"ดวงวันนี้ของคุณ",weekly:"ดวงสัปดาห์นี้ของคุณ",monthly:"ดวงเดือนนี้ของคุณ",yearly:"ดวงปีนี้ของคุณ"}; return {title:titleMap[periodType],summary:`${titleMap[periodType]}สำหรับ ${periodKey} สร้างจาก ${ruleHits.length} mock rule hits`,sections:[{heading:"ภาพรวม",body:"แนวโน้มช่วงนี้เหมาะกับการจัดลำดับความสำคัญและค่อย ๆ ลงมือทำสิ่งที่ดูแลได้จริง"},{heading:"งาน/การเรียน",body:"ควรตรวจรายละเอียดและสื่อสารความคาดหวังให้ชัดเจน เพื่อให้การทำงานร่วมกันราบรื่นขึ้น"},{heading:"การเงิน",body:"เรื่องเงินควรเน้นการทบทวนรายรับรายจ่ายและตัดสินใจอย่างรอบคอบ"},{heading:"ความสัมพันธ์",body:"การฟังอย่างตั้งใจและถามด้วยความอ่อนโยนจะช่วยลดความเข้าใจผิดได้"},{heading:"สุขภาวะ",body:"ควรให้ความสำคัญกับการพักผ่อน จังหวะชีวิต และพื้นที่เงียบ ๆ สำหรับตัวเอง"},{heading:"คำแนะนำ",body:"ใช้วิจารณญาณ เลือกก้าวเล็ก ๆ ที่ทำได้จริง และกลับมาทบทวนความรู้สึกของตัวเอง"}],disclaimer}; }
export function recordAdminAudit(sessionId:string, actorId:string, action:Extract<AuditLogEntry["action"],"admin_access_denied"|"admin_session_started"|"admin_content_approved"|"admin_content_rejected"|"admin_outbound_queued">, targetId:string, metadata:Record<string,string>={}, now=new Date("2026-05-03T09:06:00.000Z")):void { writeAudit(getState(sessionId),actorId,action,targetId,now,sanitizeAuditMetadata(metadata)); }
function sanitizeAuditMetadata(metadata:Record<string,string>):Record<string,string>{ const blocked=new Set(["birthDate","birthTime","birthPlaceText","timezone","email","name","phone","userId","calculationHash","calculation_hash","content","summary","body"]); return Object.fromEntries(Object.entries(metadata).filter(([key])=>!blocked.has(key))); }
function writeAudit(s:MockMvpState,actorId:string,action:AuditLogEntry["action"],targetId:string,now:Date,metadata:Record<string,string>){ s.auditLogs.push({id:`audit_${s.auditLogs.length+1}`,actorId,action,targetId,createdAt:now.toISOString(),metadata:sanitizeAuditMetadata(metadata)}); }
function sha256(value:string){ return createHash("sha256").update(value).digest("hex"); }
